### ISSUE TITLE
Question: Pulling site from Sapwood or Grouping

### ISSUE THREAD

**Issue by tomstuder** [seancdavis/sapwood-classic#188]
Can a site be extracted from Sapwood or set-up in a new instance on another sapwood managed server space.

Example: if a client site we manage in sapwood is asked to be pulled out due to (reason x).
- can it be?
- will it work?
# randomthought #discussion

**Comment by seancdavis** [comment]
Thanks for the question, @tomstuder.

There are two elements that make up a site in Sapwood:
1. The site's code (like a _theme_ in WordPress terminology)
2. The content structure and content

Since you track the code with git, that can certainly be pulled out an imported into another instance. You currently can not extract the content from Sapwood, although you could write a rake task within your site's code that would handle that.

That being said, v1.6 aims to make setting up a site and getting started with code much easier. I will consider exporting packaged content as part of this release.

**Comment by seancdavis** [comment]
An exporting feature will be a big part of Sapwood v2. Access to content within Sapwood will be available either via the API or an exporter. Exporters will not ship with v2.0, but they won't be far behind.
