### ISSUE TITLE
Cannot add child pages to an unpublished parent

### ISSUE THREAD

**Issue by hungrymedia** [seancdavis/sapwood-classic#235]
Creating a child page under it's unpublished parent results in the child page being created at the root level

**Comment by seancdavis** [comment]
@hungrymedia: This has been known for awhile [#148], but I can't seem to pinpoint what the heck is going on (which you can probably tell by the ridiculous history of that issue).

It only seems to happen in production, and I'm not sure why.

If you have any clues, I'm all ears. Otherwise, the answer might just be to remove the new button until the parent is published.

**Comment by hungrymedia** [comment]
My bad for the dupe. I can see that it would be handy to add a page and children before publishing, though. I'll take a gander.

**Comment by seancdavis** [comment]
Just had an idea for you, @hungrymedia.

Awhile back, to enable developers to access associations of pages on a site, I called the association `webpages`. Then the `pages` method checks your environment and filters out unpublished pages if you are in production. I bet if you find where the parent is being loaded, you can change that call to `webpages` and then set it.

That would make perfect sense, then, that I can't reproduce it in development.

**Comment by seancdavis** [comment]
Flying blind here, but will test this with a v1.5.6 release, and reopen this if that doesn't solve it.
