### ISSUE TITLE
[Sapwood]  (NoMethodError) "undefined method has_show_view?' for nil:NilClass"

### ISSUE THREAD

**Issue by hungrymedia** [seancdavis/sapwood-classic#300]
Seeing close to 2,000 such errors as below. Seems like a check for a `current_template` would do the trick on https://github.com/seancdavis/sapwood-classic/blob/master/app/controllers/viewer/pages_controller.rb#L54

```
[Sapwood]  (NoMethodError) "undefined method has_show_view?' for nil:NilClass"
A NoMethodError occurred in pages#show:

 undefined method `has_show_view?' for nil:NilClass
 app/controllers/viewer/pages_controller.rb:54:in `show'

-------------------------------
Request:
-------------------------------

 * URL        : http://ift.tt/1U1sMd7
 * HTTP Method: GET
 * IP address : 75.73.86.11
 * Parameters : {"controller"=>"viewer/pages", "action"=>"show", "page_path"=>"feed"}
 * Timestamp  : 2016-06-13 20:40:47 UTC
 * Server : tdgcms01
 * Rails root : /home/deploy/apps/taproot
 * Process: 3321

-------------------------------
Session:
-------------------------------

 * session id: nil
 * data: # 
```

**Comment by seancdavis** [comment]
Yikes!

You're right in that a check would work, but I want to dig a little deeper on this.

This section of the clause that you've pointed to means that `current_page` is present. And a page is [required to have a template](https://github.com/seancdavis/sapwood-classic/blob/master/app/controllers/viewer/pages_controller.rb#L54). We can likely assume we're getting `nil` for `current_template` because of one of [these two lines](https://github.com/seancdavis/sapwood-classic/blob/master/app/helpers/templates_helper.rb#L13-L14).

Can you confirm that the page(s) causing these errors have templates? I'm not nearly as concerned about a 500 error when a template isn't found as I am in figuring how a page ends up without a template.

**Comment by seancdavis** [comment]
@hungrymedia: I dug in and found that every page from the sample of errors that I grabbed was hitting what looked to be legacy pages (pages on an old site that were no longer valid). So this actually looks like an issue of the current page not being nil, but then having no template (because really, it should be nil).

**Comment by hungrymedia** [comment]
Ah.... So it's 500 where it should 404.

**Comment by seancdavis** [comment]
This is _still_ happening, even after these couple fixes. Trying to get to the bottom of it ...

**Comment by seancdavis** [comment]
It's quite possible this was happening because of caching. Seems unlikely, but I'm not sure. Going to watch errors that come in over the next week and see if it still needs to be addressed.
