### ISSUE TITLE
Can not Update Repo (git pull)

### ISSUE THREAD

**Issue by redman2224** [seancdavis/sapwood-classic#75]
After moving git the git repo from one hose to another, I can not update the Repo (git pull) through the admin UI. I have ensured that the git url in settings is correct.

**Comment by seancdavis** [comment]
I've found two scenarios that cause this most frequently:

**01: Sidekiq**

First, the current version (1.0.5) does not monitor the sidekiq process to ensure it stays running. This will be coming soon. 

You can check to see if sidekiq is running by logging into the server and running:

``` text
$ ps -ef | grep sidekiq
```

If you see something like this:

``` text
deploy   26962     1  0 Jan29 ?        00:04:57 sidekiq 3.3.0 taproot [0 of 25 busy]
```

Then it is running. Otherwise you need to start it.

``` text
$ cd /path/to/taproot
$ RAILS_ENV=production bundle exec rake taproot:start_sidekiq
```

**02: Git URL**

The current version does not change the remote git url in the system for your project's submodule once the project is cloned or created. You'll have to login to the server, change into your project's directory, and then run:

``` text
$ git remote set-url origin [new_url]
```

This may change in the future, or it may not be necessary at all.
