### ISSUE TITLE
Media Library - Speed

### ISSUE THREAD

**Issue by tomstuder** [seancdavis/sapwood-classic#97]
Increase load/ speed time of the media library.
- Wait time increased since we added more images (this is only the beginning)
- Clicking the button to add new image, if there is a wait - let the user know (loading)

**Comment by seancdavis** [comment]
In both cases, we need to have a paginator for files to make it more efficient to load. I also like the idea of a loading animation in the cases where it might be a little slower. Not going to do that for the library itself, but we can do that on a page form.

Because file management updates are [pushed to v1.5](https://github.com/seancdavis/sapwood/blob/v1.1/ROADMAP.md), I'll add this to a v1.1.x patch.

**Comment by seancdavis** [comment]
To refute my last comment, after much more digging into Dragonfly, it seems caching really isn't happening. You have to go a bit further to make it efficient.

Therefore, in keeping with the strategy to not get too complicated out of the gate, I'm going to revert to local file hosting and then take advantage of caching on the production server.

In addition, I'll also add an option for the max file size. A lot of times performance issues are due to files being much, much bigger than necessary in the first place. By forcing users to optimize their files before upload, this project can then focus on the resizing logic, versus unnecessarily processing images.

These improvements require a data transition, and therefore must be added to a minor release. I'll stick them in `v1.2` to ensure this gets cleaned up sooner. Expect `v1.2` in March 2015.
